# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - model: vit.yaml
  - paths: default.yaml
  - _self_

# task name, determines output directory path
task_name: "PyTorch Lightning Inference"

image_path: "https://assets.skiesmag.com/wp-content/uploads/2017/02/Air-Canada-new-livery-3-1024x634.jpg"
# image_path: "https://upload.wikimedia.org/wikipedia/commons/0/08/Chital_Deer_%28Bandhavgarh%29.jpg"

model:
  num_classes: 10

# classes: ['cat', 'dog']
classes: ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

# seed for random number generators in pytorch, numpy and python.random
seed: null

# simply provide checkpoint path to resume training
ckpt_path: ???
