# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: hp.yaml
  - model: gpt.yaml
  - paths: default.yaml
  - trainer: default.yaml
  - logger: null
  - callbacks: default.yaml
  - hydra: default.yaml
  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null
  - hparam: default.yaml
  
# task name, determines output directory path
task_name: "train"

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# compile model for faster training with pytorch 2.0
compile: False

# hyperparameter search flag
tune_hparam: False

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null

# limit train batches for debugging purposes
limit_train_batches: 1.0 #0.1

# limit val batches for debugging purposes
limit_val_batches: 1.0 #0.1

# limit test batches for debugging purposes
limit_test_batches: 1.0 #0.1

# tracing flag, set True to enable torch.jit.trace model
trace: True

# scripting flag, set True to enable torch.jit.script model
script: True

# model name, used for saving scripting and tracing models
model_name: null