help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	rm -rf build
	rm -rf .pytest_cache
	rm -r *.egg-info
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

install: ## Install package
	pip3 install -e .

train: ## Train model
	lightningtrain_train data.num_workers=16

eval:	## Evaluate model
	lightningtrain_eval

test-full: ## Run tests
	pytest

docker-build: ## Build docker image
	docker build -t lightningtrain .

docker-run: ## Run docker image
	docker run -it lightningtrain bash

docker-push: ## Push docker image
	docker tag lightningtrain:latest santuhazra1/lightningtrain:latest
	docker push santuhazra1/lightningtrain:latest

pypi-build: ## Build package
	python3 setup.py bdist_wheel --universal

pypi-push: ## Push to pypi
	python3 -m twine upload dist/*