# Stage 1:
FROM python:3.9-slim as build
    
COPY requirements.txt .

# # installing python packages from requirements.txt
RUN python3 -m pip install --user -r requirements.txt --ignore-installed && rm -rf /root/.cache/pip


# Stage 2:
FROM gcr.io/distroless/python3-debian11

COPY --from=build /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH

WORKDIR /workspace

COPY . .

ENTRYPOINT ["python3", "demo_gpt.py"]

# # using cuda 11.3.0 and cudnn 8 docker image as base image for development environment
# FROM python:3.9-slim as build

# # setting non-interactive mode
# ENV DEBIAN_FRONTEND=noninteractive

# # creating a non-root user
# ARG USERNAME=developer
# ARG USER_UID=1000
# ARG USER_GID=$USER_UID

# # setting timezone
# RUN ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

# # installing basic dependencies
# RUN apt update && apt install --no-install-recommends -y \
#     git \
#     curl \
#     build-essential \
#     sudo \
#     ssh \
#     software-properties-common


# # setting working directory to /workspace
# WORKDIR /workspace

# # //copy requirements from parent directory
# ADD requirements.txt .

# # installing python packages from requirements.txt
# RUN python3 -m pip install --upgrade pip && python3 -m pip install setuptools wheel
# RUN python3 -m pip install -r requirements.txt --ignore-installed && rm -rf /root/.cache/pip

# # copying all files from parent directory
# COPY . .

# WORKDIR /workspace