# Stage 1:
FROM python:3.9-slim as build
    
COPY requirements.txt .

# # installing python packages from requirements.txt
RUN python3 -m pip install -r requirements.txt && rm -rf /root/.cache/pip
ENV PATH=/root/.local/bin:$PATH

WORKDIR /workspace

COPY . .

CMD ["gunicorn", "server:app", "--workers", "2", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8080"]