_target_: lightningtrain.models.cifar10_module.CIFAR10LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: lightningtrain.models.components.resnet_cifar10.ResNet
  num_blocks: [2 , 2, 2, 2]
  num_classes: 10
  norm: "batchnorm"