# using cuda 11.3.0 and cudnn 8 docker image as base image for development environment
FROM nvidia/cuda:11.7.0-cudnn8-runtime-ubuntu22.04

# setting non-interactive mode
ENV DEBIAN_FRONTEND=noninteractive

# creating a non-root user
ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# setting timezone
RUN ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

# installing basic dependencies
RUN apt update && apt install --no-install-recommends -y \
    git \
    curl \
    build-essential \
    sudo \
    ssh \
    python3.10-dev \
    software-properties-common

# installing python3.10
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt update && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

# setting working directory to /workspace
WORKDIR /workspace

# //copy requirements from parent directory
ADD requirements.txt .

# installing python packages from requirements.txt
RUN python3.10 -m pip install --upgrade pip && python3.10 -m pip install setuptools wheel
RUN python3.10 -m pip install -r requirements.txt --ignore-installed && rm -rf /root/.cache/pip

# copying all files from parent directory
COPY . .

# adding dev user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -G audio,users -ms /bin/bash $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME
