# using cuda 11.3.0 and cudnn 8 docker image as base image for development environment
FROM nvidia/cuda:12.1.0-devel-ubuntu22.04

# setting non-interactive mode
ENV DEBIAN_FRONTEND=noninteractive

# creating a non-root user
ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# setting timezone
RUN ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

# installing basic dependencies
RUN apt update && apt install --no-install-recommends -y \
    git \
    curl \
    build-essential \
    sudo \
    ssh \
    software-properties-common

# installing python3.10
RUN add-apt-repository ppa:deadsnakes/ppa && \
    apt update && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3

# setting working directory to /workspace
WORKDIR /workspace

# //copy requirements from parent directory
ADD requirements.txt .

# # installing python packages from requirements.txt
RUN python3 -m pip install --upgrade pip && python3 -m pip install setuptools wheel
RUN python3 -m pip install -r requirements.txt --ignore-installed && rm -rf /root/.cache/pip

# # # copying all files from parent directory
# COPY . .

# RUN python3 -m pip install -e .

# # CMD ["lightningtrain_train", "experiment=cifar10", "data.num_workers=8"]
# CMD ["lightningtrain_train", "-m", "hydra/launcher=joblib", "hydra.launcher.n_jobs=1", "experiment=cifar10", "model.patch_size=2,4,8,16", "data.num_workers=8"]
