_target_: lightningtrain.models.gpt_module.GPTLitModule
learning_rate: 0.001
block_size: ${data.block_size}

model:
  _target_: lightningtrain.models.components.gpt.GPT
  vocab_size: 100277
  block_size: ${data.block_size}
  n_embed: 128
  n_decoder_blocks: 4
  drop_p: 0.
  n_heads: 4